include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    curly_braces_in_flow_control_structures: false
    constant_identifier_names: false
    unnecessary_null_in_if_null_operators: false
    prefer_typing_uninitialized_variables: false
    must_be_immutable: false
    use_key_in_widget_constructors: false
    body_might_complete_normally_nullable: false
    avoid_print: false
    avoid_unnecessary_containers: false
    prefer_final_fields: false
    
